### ISSUE TITLE
Doesn't work on my machine

### ISSUE THREAD

**Issue by doubleswirve** [SamSamDataMan/Data-Viz-Gallery#1]
I'm deeply concerned about some of the dangerous assumptions you're making here: https://github.com/SamSamDataMan/Data-Viz-Gallery/blob/d2c333920cb0d927d455818734964b391d924ade/datavizgallery.py#L9

Care to address?

**Comment by SamSamDataMan** [comment]
Thank you for bringing this grave error to our attention. We hope the most recent patch will allay your concerns.

**Comment by doubleswirve** [comment]
Now that's what I'm talking about! 💥
